// <auto-generated />
using System;
using Leaf2Google.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leaf2Google.Migrations
{
    [DbContext(typeof(LeafContext))]
    [Migration("20220827181934_Update_5")]
    partial class Update_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Leaf2Google.Models.Generic.Audit<Leaf2Google.Models.Leaf.Leaf>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("Context")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerLeafId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerLeafId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("Leaf2Google.Models.Leaf.Leaf", b =>
                {
                    b.Property<Guid>("LeafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("IV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("NissanPasswordBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NissanUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeafId");

                    b.ToTable("Leafs");
                });

            modelBuilder.Entity("Leaf2Google.Models.Generic.Audit<Leaf2Google.Models.Leaf.Leaf>", b =>
                {
                    b.HasOne("Leaf2Google.Models.Leaf.Leaf", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerLeafId");

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
