// <auto-generated />
using System;
using Leaf2Google.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leaf2Google.Migrations
{
    [DbContext(typeof(LeafContext))]
    [Migration("20220830204719_Update_12")]
    partial class Update_12
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Leaf2Google.Models.Generic.Audit<Leaf2Google.Models.Leaf.Leaf>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("Context")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerLeafId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OwnerLeafId");

                    b.ToTable("t_leafs_audit", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.Auth", b =>
                {
                    b.Property<Guid>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerLeafId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthId");

                    b.HasIndex("OwnerLeafId");

                    b.ToTable("t_auths_auth", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.Token", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerAuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("TokenId");

                    b.HasIndex("OwnerAuthId");

                    b.ToTable("t_auths_token", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Leaf.Leaf", b =>
                {
                    b.Property<Guid>("LeafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("NissanPasswordBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NissanUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryVin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeafId");

                    b.ToTable("t_leafs_leaf", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Generic.Audit<Leaf2Google.Models.Leaf.Leaf>", b =>
                {
                    b.HasOne("Leaf2Google.Models.Leaf.Leaf", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerLeafId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.Auth", b =>
                {
                    b.HasOne("Leaf2Google.Models.Leaf.Leaf", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerLeafId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.Token", b =>
                {
                    b.HasOne("Leaf2Google.Models.Google.Auth", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
