// <auto-generated />
using System;
using Leaf2Google.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Leaf2Google.Migrations
{
    [DbContext(typeof(LeafContext))]
    [Migration("20221003192944_Update-22")]
    partial class Update22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fido2NetLib.Development.StoredCredential", b =>
                {
                    b.Property<byte[]>("UserId")
                        .HasColumnType("varbinary(900)");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("UserHandle")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UserId");

                    b.ToTable("t_leafs_securitykey", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("StoredCredential");
                });

            modelBuilder.Entity("Leaf2Google.Models.Car.CarModel", b =>
                {
                    b.Property<Guid>("CarModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("IV")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("NissanPasswordBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NissanUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarModelId");

                    b.ToTable("t_leafs_leaf", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Generic.AuditModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("Context")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Owner")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("t_leafs_audit", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Generic.ConfigModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("t_app_config", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.AuthModel", b =>
                {
                    b.Property<Guid>("AuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastExecute")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastQuery")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OwnerCarModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedirectUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthId");

                    b.HasIndex("OwnerCarModelId");

                    b.ToTable("t_auths_auth", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.TokenModel", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccessToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerAuthId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RefreshToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("TokenId");

                    b.HasIndex("OwnerAuthId");

                    b.ToTable("t_auths_token", (string)null);
                });

            modelBuilder.Entity("Leaf2Google.Models.Security.StoredCredentialModel", b =>
                {
                    b.HasBaseType("Fido2NetLib.Development.StoredCredential");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.ToTable("t_leafs_securitykey", (string)null);

                    b.HasDiscriminator().HasValue("StoredCredentialModel");
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.AuthModel", b =>
                {
                    b.HasOne("Leaf2Google.Models.Car.CarModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerCarModelId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Leaf2Google.Models.Google.TokenModel", b =>
                {
                    b.HasOne("Leaf2Google.Models.Google.AuthModel", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerAuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });
#pragma warning restore 612, 618
        }
    }
}
